---
name: SignShop
main: SignShop\SignShop
version: 0.1
api: 1.0.0
description: Official plugin for Pocketmine API 1.0.0 
website: http://zazzamcpe.tk
commands:
 sign:
  description: "Command to manage some sign on the server server"
  