---
name: SignShop
main: SignShop\SignShop
version: 1.1.2
api: [1.11.0]
load: POSTWORLD
author: xionbig
authors: [xionbig]
description: "Buy and Sell the items using Signs with virtual-money."
website: http://xionbig.eu/plugins/SignShop 
permissions:
 sign:
  default: notop
  description: "Allows do all that SignShop"
  children:
   sign.command:
    default: true
    description: "Allows using all the SignShop commands"