---
name: SignShop
main: SignShop\SignShop
version: 3.0.0
api: [2.0.0]
load: POSTWORLD
author: NikoZazza
authors: [NikoZazza]
description: "Buy and Sell the items using Signs with virtual-money."
website: http://nikozazza.sixcosoft.net/plugins/SignShop
permissions:
 sign:
  default: notop
  description: "Allows do all that SignShop"
  children:
   sign.command:
    default: true
    description: "Allows using all the SignShop commands"